"""Report Writer Agent: assembles final Markdown/HTML report with TOC and bibliography."""
import json
import logging
import re
from typing import List, Dict
from datetime import datetime

from langchain_core.messages import HumanMessage, SystemMessage

from app.core.config import get_llm_client
from app.core.state import ResearchState, ProgressUpdate, AgentStatus

logger = logging.getLogger(__name__)

REPORT_SYSTEM = """You are a senior academic editor. Your task is to assemble a polished research report.
Write in clear, formal academic prose. The report should be comprehensive yet readable.
Do NOT add any content not present in the synthesized sections.
Generate only a brief introduction and conclusion that tie the sections together."""

REPORT_INTRO_PROMPT = """Research topic: {topic}

Synthesized sections summary:
{sections_summary}

Write a 2-3 paragraph introduction for this research report that:
1. Contextualizes the topic
2. States the scope of the research
3. Outlines the structure of the report

Respond with ONLY the introduction text (no headers, no JSON)."""

REPORT_CONCLUSION_PROMPT = """Based on these synthesized research findings:

{sections_summary}

Write a 2-3 paragraph conclusion that:
1. Synthesizes the key findings
2. Notes limitations of the sources/research
3. Suggests directions for further research

Respond with ONLY the conclusion text (no headers, no JSON)."""


async def run_report_writer(state: ResearchState) -> ResearchState:
    """Assemble the final research report."""
    logger.info("[ReportWriter] Assembling final report")

    progress = list(state.get("progress", []))
    progress.append(ProgressUpdate(
        agent="report_writer",
        status=AgentStatus.RUNNING,
        message="Đang viết báo cáo hoàn chỉnh..."
    ))

    topic = state.get("topic", "Research Report")
    synthesized_sections = state.get("synthesized_sections", [])
    all_sources = state.get("all_sources", {})
    credible_sources = state.get("credible_sources", {})
    discarded_sources = state.get("discarded_sources", {})

    llm = get_llm_client()

    # Generate introduction
    sections_summary = _build_sections_summary(synthesized_sections)
    intro_response = await llm.ainvoke([
        SystemMessage(content=REPORT_SYSTEM),
        HumanMessage(content=REPORT_INTRO_PROMPT.format(
            topic=topic, sections_summary=sections_summary[:3000]
        ))
    ])
    introduction = intro_response.content.strip()

    # Generate conclusion
    conclusion_response = await llm.ainvoke([
        SystemMessage(content=REPORT_SYSTEM),
        HumanMessage(content=REPORT_CONCLUSION_PROMPT.format(
            sections_summary=sections_summary[:3000]
        ))
    ])
    conclusion = conclusion_response.content.strip()

    # Build bibliography (APA format)
    bibliography = _build_bibliography(all_sources, synthesized_sections)

    # Assemble complete report
    report_md = _assemble_markdown_report(
        topic=topic,
        introduction=introduction,
        sections=synthesized_sections,
        conclusion=conclusion,
        bibliography=bibliography,
        all_sources=all_sources,
        credible_sources=credible_sources,
        discarded_sources=discarded_sources,
    )

    progress.append(ProgressUpdate(
        agent="report_writer",
        status=AgentStatus.COMPLETED,
        message="Báo cáo hoàn thành!",
        data={"word_count": len(report_md.split()), "sources_cited": len(bibliography)}
    ))

    state["final_report"] = report_md
    state["bibliography"] = bibliography
    state["progress"] = progress
    state["status"] = "completed"
    return state


def _build_sections_summary(sections: List[dict]) -> str:
    parts = []
    for s in sections:
        q = s.get("sub_question", "")
        content_preview = s.get("content", "")[:300]
        parts.append(f"**{q}**\n{content_preview}...")
    return "\n\n".join(parts)


def _assemble_markdown_report(
    topic: str,
    introduction: str,
    sections: List[dict],
    conclusion: str,
    bibliography: List[str],
    all_sources: Dict,
    credible_sources: Dict,
    discarded_sources: Dict,
) -> str:
    now = datetime.now().strftime("%B %d, %Y")
    total_credible = sum(len(v) for v in credible_sources.values())
    total_discarded = sum(len(v) for v in discarded_sources.values())

    lines = []

    # Title
    lines.append(f"# {topic}")
    lines.append(f"\n*Generated by AI Research Agent — {now}*\n")

    # Table of Contents
    lines.append("## Table of Contents\n")
    lines.append("1. [Introduction](#introduction)")
    for i, s in enumerate(sections, 2):
        q = s.get("sub_question", f"Section {i}")
        anchor = _to_anchor(q)
        lines.append(f"{i}. [{q}](#{anchor})")
    lines.append(f"{len(sections)+2}. [Conclusion](#conclusion)")
    lines.append(f"{len(sections)+3}. [Source Quality Report](#source-quality-report)")
    lines.append(f"{len(sections)+4}. [Bibliography](#bibliography)")
    lines.append("")

    # Introduction
    lines.append("## Introduction\n")
    lines.append(introduction)
    lines.append("")

    # Sections
    for s in sections:
        q = s.get("sub_question", "")
        content = s.get("content", "")
        citations = s.get("citations", [])

        lines.append(f"## {q}\n")
        lines.append(content)
        lines.append("")

        # Inline source notes for this section
        if citations:
            lines.append("> **Sources used in this section:**")
            for c in citations:
                lines.append(f"> - [{c['title'] or c['url']}]({c['url']}) — Score: {c.get('score', '?'):.1f}/10")
            lines.append("")

    # Conclusion
    lines.append("## Conclusion\n")
    lines.append(conclusion)
    lines.append("")

    # Source Quality Report
    lines.append("## Source Quality Report\n")
    lines.append(f"**Total sources evaluated:** {total_credible + total_discarded}")
    lines.append(f"**Credible sources (threshold ≥ {5.0}):** {total_credible}")
    lines.append(f"**Discarded sources:** {total_discarded}\n")

    if all_sources:
        lines.append("### Credible Sources\n")
        lines.append("| # | Title | Score | Domain | Recency | Quality |")
        lines.append("|---|-------|-------|--------|---------|---------|")
        credible_list = [s for s in all_sources.values() if s.get("is_credible")]
        credible_list.sort(key=lambda x: x.get("total_score", 0), reverse=True)
        for i, s in enumerate(credible_list, 1):
            title = (s.get("title") or s.get("url", ""))[:50]
            lines.append(
                f"| {i} | [{title}]({s.get('url', '#')}) | "
                f"**{s.get('total_score', 0):.1f}** | "
                f"{s.get('domain_score', 0):.1f} | "
                f"{s.get('recency_score', 0):.1f} | "
                f"{s.get('llm_judge_score', 0):.1f} |"
            )
        lines.append("")

        # Discarded sources with reasons
        discarded_list = [s for s in all_sources.values() if not s.get("is_credible")]
        if discarded_list:
            lines.append("### Discarded Sources\n")
            lines.append("<details><summary>Click to expand discarded sources</summary>\n")
            for s in discarded_list:
                title = (s.get("title") or s.get("url", ""))[:60]
                lines.append(f"- **[{title}]({s.get('url', '#')})** — Score: {s.get('total_score', 0):.1f}/10")
                lines.append(f"  > {s.get('explanation', 'No explanation')}")
            lines.append("</details>\n")

    # Bibliography
    lines.append("## Bibliography\n")
    for i, ref in enumerate(bibliography, 1):
        lines.append(f"{i}. {ref}")
    lines.append("")

    return "\n".join(lines)


def _build_bibliography(all_sources: Dict, sections: List[dict]) -> List[str]:
    """Build APA-style bibliography from cited sources."""
    used_ids = set()
    for s in sections:
        for c in s.get("citations", []):
            used_ids.add(c["source_id"])

    refs = []
    for sid, source in all_sources.items():
        if sid not in used_ids and source.get("is_credible"):
            used_ids.add(sid)

    for sid in used_ids:
        source = all_sources.get(sid)
        if not source:
            continue
        ref = _format_apa(source)
        refs.append(ref)

    return sorted(refs)


def _format_apa(source: dict) -> str:
    """Format a source in APA style."""
    title = source.get("title", "Untitled")
    url = source.get("url", "")
    date = source.get("published_date", "n.d.")
    if date and len(str(date)) == 4:
        year = date
    elif date:
        try:
            from dateutil import parser as dateparser
            year = str(dateparser.parse(str(date)).year)
        except Exception:
            year = str(date)
    else:
        year = "n.d."

    domain = ""
    try:
        import tldextract
        ext = tldextract.extract(url)
        domain = f"{ext.domain}.{ext.suffix}".title()
    except Exception:
        domain = url[:30]

    return f"{domain}. ({year}). *{title}*. Retrieved from {url}"


def _to_anchor(text: str) -> str:
    return re.sub(r'[^a-z0-9-]', '', text.lower().replace(' ', '-'))
